Add sql editing function
pingcap/tiunimanager pull request #898
Opened 2023-02-01 01:50 UTC by rivenwang

The new api added includes the management addition, deletion, modification and query of sql file and the opening and closing of session, etc.

2023-02-03 07:52 UTC, haiboumich requested changes

2023-02-03 07:52 UTC, haiboumich commented on micro-api/controller/dataapps/sqleditor/sqleditor_api.go
> +// @Router /{cluster_id}/session [post]
maybe the @Router should start with '/dataapps/sqleditor/' ? Like '/dataapps/sqleditor/{cluster_id}/session'.
Same for the rest routers.

2023-02-03 07:52 UTC, haiboumich commented on micro-cluster/dataapps/sqleditor/main_test.go
> +package sqleditor
Please add copyright

2023-02-03 07:52 UTC, haiboumich commented on micro-cluster/dataapps/sqleditor/manager_test.go
> +package sqleditor
please add copyright

2023-02-03 07:52 UTC, haiboumich commented on models/dataapps/sqleditor/dbagent/main_test.go
> +package dbagent
please add copyright

2023-02-03 07:52 UTC, haiboumich commented on models/dataapps/sqleditor/dbagent/readwriteimpl_test.go
> +package dbagent
please add copyright

2023-02-03 07:52 UTC, haiboumich commented on models/dataapps/sqleditor/dbagent/sessioncache.go
> +package dbagent
please add copyright

2023-02-03 07:52 UTC, haiboumich commented on models/dataapps/sqleditor/dbagent/sessioncache_test.go
> +package dbagent
please add copyright

2023-02-03 07:52 UTC, haiboumich commented on models/dataapps/sqleditor/sqlfile/main_test.go
> + * Copyright (c)  2022 PingCAP                                                *
2023

2023-02-03 07:52 UTC, haiboumich commented on models/dataapps/sqleditor/sqlfile/readwriteimpl_test.go
> +package sqleditorfile
please add copyright

2023-02-03 07:52 UTC, haiboumich commented on util/api/tidb/sql/clustermeta.go
> + * Copyright (c)  2022 PingCAP                                                *
2023

2023-02-07 07:54 UTC, haiboumich approved these changes
LGTM

2023-02-09 01:59 UTC, rivenwang commented
merge

2023-02-09 02:01 UTC, haiboumich commented
/merge

2023-02-09 02:29 UTC, zhangpeijin-milo approved these changes
LGTM

2023-02-09 02:59 UTC, rivenwang commented
/merge

2023-02-09 03:02 UTC, rivenwang commented
/assign @haiboumich

2023-02-09 04:35 UTC, haiboumich commented
/merge

2023-02-09 06:14 UTC, haiboumich commented
/merge

2023-02-09 06:26 UTC, rivenwang commented
/merge

2023-02-09 07:02 UTC, haiboumich commented
/merge

2023-02-09 07:12 UTC, merged